### ISSUE TITLE
Can't access lexical declaration `window' before initialization

### ISSUE THREAD

**Issue by faressallam** [jinzocode/imacros-scripts#2]
Hello 
i cant run the script , can you help me ?

**Comment by jinzocode** [comment]
Hello

Which script would you like to run?

**Comment by faressallam** [comment]
twitter scripts specially account creator

**Comment by jinzocode** [comment]
Please follow **README** instructions:
https://github.com/jinzocode/imacros-scripts/blob/master/README.md

**Download** Firefox ESR 52/iMacros 8.9.7 Then follow **How to use?**

Don't hesitate if you have any other queries.
Thanks

**Comment by faressallam** [comment]
i did follow the instructions , but i always get error with most of twitter scripts  .
this is the error i get : 
ReferenceError: can't access lexical declaration `window' before initialization, line 6 (Error code: -991)

thank you for you attention :)

**Comment by jinzocode** [comment]
Thanks for reporting this issue.

it has been fixed https://github.com/jinzocode/imacros-scripts/commit/f210859c2c8cea45e3d7ba62f2368b8ce1395452

**Comment by faressallam** [comment]
thank you , but i test it now and i get this error  : Error: Accessing content window is not supported in multiprocess Firefox, line 208 (Error code: -991)
is that from the browser ?

**Comment by jinzocode** [comment]
Yes this from the browser, please use Firefox 52 ESR.

**Comment by faressallam** [comment]
i did :( 
http://prntscr.com/jvmcpz

**Comment by jinzocode** [comment]
Make sure you've disabled auto update for iMacros, and you've version 8.7.9.

**Comment by faressallam** [comment]
i reinstall imacros and firefox and its work 
but creating accounts module is stoppen at this page : http://prntscr.com/jvmirn

**Comment by jinzocode** [comment]
Seems like twitter has updated the web forms.
Scripts will be updated as soon as possible to identify new fields.

**Comment by faressallam** [comment]
Great , thank you :)
